### ISSUE TITLE
Background is forced to white|black

### ISSUE THREAD

**Issue by nelson6e65** [sindresorhus/generate-github-markdown-css#16]
Background (`--color-canvas-default`) is forced to `black` and `white`.

To use on editors, like Visual Studio, not all themes are `black`|`white`.

I know I can publish my own style, but it would be nice to have an extra CSS file published with transparent background in the official CDN. Like:

```css
/* github-markdown-with-transparent-background.css */

@media (prefers-color-scheme: dark) {
  .markdown-body {
    --color-canvas-default: #00000000;
  }
}

@media (prefers-color-scheme: light) {
  .markdown-body {
    --color-canvas-default: #ffffff00;
  }
}
```

So we can import at the end, like:

![imagen](https://user-images.githubusercontent.com/9272498/193439650-ba537b0e-514b-4f79-a693-2d9d9bf6d340.png)
