### ISSUE TITLE
Include styles for user/team mentions

### ISSUE THREAD

**Issue by kj800x** [sindresorhus/generate-github-markdown-css#8]
## Description
The styling of user/team mentions is different between `github-markdown-css` and the actual styling on GitHub. I'm not sure if there is an easy fix, since I don't think you can mention a user or team in your `fixture.md`; this styling seems to only apply in the body of pull requests/issues/comments.

My coworkers identified at least some of the missing styles:
```css
.team-mention, .user-mention {
    font-weight: 600;
    color: #24292e;
    white-space: nowrap;
}
```

## `github-markdown-css` styles:
<img width="797" alt="Screen Shot 2020-04-29 at 5 59 09 PM" src="https://user-images.githubusercontent.com/1657142/80651417-e6551900-8a43-11ea-9c1e-6542728cfa84.png">

## Actual GitHub styles: 
<img width="746" alt="Screen Shot 2020-04-29 at 6 00 32 PM" src="https://user-images.githubusercontent.com/1657142/80651416-e5bc8280-8a43-11ea-8076-1a7bf4272f19.png">

/cc @also @jhilker

**Comment by kj800x** [comment]
I also just noted that PR bodies have a `comment-body` class which is why the font size wasn't matching up either.

```css
.comment-body {
  font-size: 14px;
}
```
